### ISSUE TITLE
Vendor vs Inventory 

### ISSUE THREAD

**Issue by CNagel314** [cs481a3termproject/TermProject#16]
In Registry.sol, there is a constructor for the inventory and one that takes the vendor name as an argument. If a vendor is creating a registry, we want to call the inventory constructor as well assumedly. Need to also deal with a vendor adding a second register and how to deal with the inventory in that instance, ie. Shared inventory between two registers.

**Comment by 0kayla0** [comment]
Fixed the constructors and created new issue for shared inventory.
